name: Build and Publish
on: [push]

jobs:
  buildAndPublish:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build the Docker container image
        run: docker build -f Dockerfile -t jinze1991/kubedeploy:latest .

      - name: Push the image to Docker hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker push jinze1991/kubedeploy:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
